str = ''
str += '<div class="local">'
str += '	<a href="javascript:">'
str += '		<span>전체</span>'
str += '		<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="12" height="12"><path fill="none" d="M0 0h24v24H0z"/><path d="M13 16.172l5.364-5.364 1.414 1.414L12 20l-7.778-7.778 1.414-1.414L11 16.172V4h2v12.172z"/></svg>'
str += '	</a>'
str += '</div>'
str += '<div id="popup" class="popup">'
str += '	<div class="popup_inner">'
str += '		<div class="keyword k2">'
str += '			<ul class="filters">'
str += '				<li><a href="javascript:" data-filters="전체">#전체</a></li>'
str += '				<li><a href="javascript:" data-filters="강아지">#강아지</a></li>'
str += '				<li><a href="javascript:" data-filters="고양이">#고양이</a></li>'
str += '				<li><a href="javascript:" data-filters="돼지">#돼지</a></li>'
str += '				<li><a href="javascript:" data-filters="열대어">#열대어</a></li>'
str += '				<li><a href="javascript:" data-filters="다람쥐">#다람쥐</a></li>'
str += '				<li><a href="javascript:" data-filters="거북이">#거북이</a></li>'
str += '				<li><a href="javascript:" data-filters="돌고래">#돌고래</a></li>'
str += '				<li><a href="javascript:" data-filters="도마뱀">#도마뱀</a></li>'
str += '				<li><a href="javascript:" data-filters="앵무새">#앵무새</a></li>'
str += '				<li><a href="javascript:" data-filters="고슴도치">#고슴도치</a></li>'
str += '				<li><a href="javascript:" data-filters="페럿">#페럿</a></li>'
str += '			</ul>'
str += '		</div>'
str += '	</div>'
str += '	<button id="popup_close" class="popup_close">'
str += '		<span>닫기</span>'
str += '	</button>'
str += '</div>'

document.write( str );